### ISSUE TITLE
Practica de hilos Reporte

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/practica-de-hilos-Aricel117#2]
[Practica de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Aricel117/files/6525759/Practica.de.Hilos.pdf)

**Comment by garaudy12** [comment]
Calificación 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
